version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    command: "./s/wait-for-it.sh db:5432 -- gunicorn --bind :8000 social_web_page.wsgi:application"
    build: .
    stdin_open: true
    restart: always
    tty: true
    volumes:
      - .:/code
    ports:
      - 80:8000
    depends_on:
      - db
    environment:
      PRODUCTION: 'true'
      DJANGO_SETTINGS_MODULE: social_web_page.settings

volumes:
  postgres_data:
