# Generated by Django 2.1.7 on 2019-03-25 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities_light', '0008_city_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('address1', models.CharField(max_length=1024)),
                ('address2', models.CharField(blank=True, max_length=1024)),
                ('postal_code', models.CharField(max_length=64)),
                ('contact_email', models.CharField(max_length=256)),
                ('birthday', models.DateField()),
                ('citizenship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.City')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isco_08_code', models.CharField(max_length=16)),
                ('experience_level', models.IntegerField(choices=[(1, 'Fundamental Awareness (basic knowledge)'), (2, 'Novice (limited experience)'), (3, 'Intermediate (practical application)'), (4, 'Advanced (applied theory)'), (5, 'Expert (recognized authority)')])),
            ],
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='work_experience',
            field=models.ManyToManyField(blank=True, to='jobseekers.WorkExperience'),
        ),
    ]
